translate:
    cellType: celltype
    expr: expression
    expr_next: expression_next

readable:
    gene_chr: Chromosome

table_columns:
    mouse:
        -
            - Gene Name
            - human_name
        -
            - Cell Type
            - cell
        -
            - Expression (TPM)
            - expression
        -  
            - Fold Enrichment
            - enrichment
    human:
        -
            - Gene ID
            - _id
        -
            - Gene Name
            - gene_name
        -
            - Source
            - source
        -
            - Chromosome
            - gene_chr
        -
            - Bodymap
            - bodymap
table_input:
    mouse:
        -
            name: Expression (TPM)
            column: expression
            type: slider
            scale: logarithmic
            min: 0
            max: 70000
            step: 10
            init:
                - 0
                - 70000
        -
            name: Fold Enrichment
            column: enrichment
            type: slider
            scale: logarithmic
            min: 5
            max: 5000
            step: 10
            init:
                - 5
                - 5000
        -
            name: Result Limit
            column: limit
            type: slider
            scale: linear
            min: 0
            max: 1000
            step: 10
            init: 100
        -
            name: Cell Type
            column: celltype
            type: selection
            options:
                - astrocyte
                - striatalNeuron
                - oligodendrocyte
                - microglia
    human:
        -
            name: Result Limit
            column: limit
            type: slider
            scale: linear
            min: 0
            max: 1000
            step: 10
            init: 100
        -
            name: Test
            column: test
            type: selection
            options:
                - a
                - b
                - c
                - d
                - d

order:
    mouse:
        - _id
        - human_id
        - human_name
        - type
        - expression
        - enrichment
    human:
        - human_id
        - _id
        - gene_name
        - chr
        - source
    celltypes:
        - neuron
        - pyramidal neuron
        - interneuron
        - astrocyte
        - microglia
        - endothelial
        - oligodendrocyte
        - medium spiny neuron
        - ependymal
brainspan:
    regions:
        - HIP
        - AMY
        - STR
        - MD
        - CBC